#!/bin/bash
set +e # be tolerent

~/.screenlayout/dualscreen.sh &
volumeicon &
parcellite &
xsetroot -solid "#333333"
xrandr --output VGA-0 --primary
#nitrogen --restore

## Set startup volume
amixer set Master 20% &
amixer set Master unmute &
amixer set PCM 80% &
amixer set PCM unmute &

aplay ~/yourstartupmusic.wav &

### OSD
dunst &

REMIND_FILE=~/.remind.txt
if [ -f $REMIND_FILE ]; then
  REMIND=`cat $REMIND_FILE`
  {
  while true
  do
    notify-send -t 5000 -u critical 'Rappel' "$REMIND"
    sleep 300
  done
  }&
fi
