#!/bin/sh

volumeicon &
parcellite &

xsetroot -solid "#333333"
#nitrogen --restore

### OSD
dunst &

## Set startup volume
exec "amixer set Master 20%"
exec "amixer set Master unmute"
exec "amixer set PCM 80%"
exec "amixer set PCM unmute"
exec "aplay ~/yourstartupmusic.wav"
